// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwknncursthenghqgevl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3a25uY3Vyc3RoZW5naHFnZXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzEyMjcsImV4cCI6MjA1MjU0NzIyN30.EkCBv3biI6fAom63l6-UbYeRpdfm4BO3S1xR7YP7dhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);