
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwknncursthenghqgevl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3a25uY3Vyc3RoZW5naHFnZXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzEyMjcsImV4cCI6MjA1MjU0NzIyN30.EkCBv3biI6fAom63l6-UbYeRpdfm4BO3S1xR7YP7dhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  { 
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (...args) => {
        console.log("Supabase API call:", args[0]);
        return fetch(...args);
      }
    }
  }
);

// Initialize storage bucket check
(async () => {
  try {
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    if (error) {
      console.error("Error listing buckets:", error);
      return;
    }
    
    const audioBucketExists = buckets.some(bucket => bucket.name === 'audio');
    const mediaBucketExists = buckets.some(bucket => bucket.name === 'media');
    
    if (!audioBucketExists) {
      console.log("Creating 'audio' bucket...");
      await supabase.storage.createBucket('audio', {
        public: true,
        fileSizeLimit: 52428800 // 50MB
      });
      console.log("'audio' bucket created successfully");
    }
    
    if (!mediaBucketExists) {
      console.log("Creating 'media' bucket...");
      await supabase.storage.createBucket('media', {
        public: true,
        fileSizeLimit: 5242880 // 5MB
      });
      console.log("'media' bucket created successfully");
    }
  } catch (err) {
    console.error("Error initializing storage buckets:", err);
  }
})();
