

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwknncursthenghqgevl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3a25uY3Vyc3RoZW5naHFnZXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzEyMjcsImV4cCI6MjA1MjU0NzIyN30.EkCBv3biI6fAom63l6-UbYeRpdfm4BO3S1xR7YP7dhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  { 
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: function(input, init) {
        console.log("Supabase API call:", input);
        return fetch(input, init);
      }
    }
  }
);

// Initialize storage bucket check
(async () => {
  try {
    console.log("Checking and initializing Supabase storage buckets...");
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    if (error) {
      console.error("Error listing buckets:", error);
      return;
    }
    
    const audioBucketExists = buckets.some(bucket => bucket.name === 'audio');
    const mediaBucketExists = buckets.some(bucket => bucket.name === 'media');
    
    if (!audioBucketExists) {
      console.log("Creating 'audio' bucket...");
      const { error: createError } = await supabase.storage.createBucket('audio', {
        public: true,
        fileSizeLimit: 52428800 // 50MB
      });
      
      if (createError) {
        console.error("Error creating 'audio' bucket:", createError);
      } else {
        console.log("'audio' bucket created successfully");
      }
    } else {
      console.log("'audio' bucket already exists");
      
      // Make sure bucket is public
      try {
        const { error: updateError } = await supabase.storage.updateBucket('audio', {
          public: true
        });
        
        if (updateError) {
          console.error("Error updating 'audio' bucket to public:", updateError);
        } else {
          console.log("'audio' bucket updated to be public");
        }
      } catch (updateErr) {
        console.error("Failed to update 'audio' bucket:", updateErr);
      }
    }
    
    if (!mediaBucketExists) {
      console.log("Creating 'media' bucket...");
      const { error: createError } = await supabase.storage.createBucket('media', {
        public: true,
        fileSizeLimit: 5242880 // 5MB
      });
      
      if (createError) {
        console.error("Error creating 'media' bucket:", createError);
      } else {
        console.log("'media' bucket created successfully");
      }
    } else {
      console.log("'media' bucket already exists");
    }
  } catch (err) {
    console.error("Error initializing storage buckets:", err);
  }
})();

